# Generated by Django 3.2.20 on 2023-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0002_alter_student_lvl_level_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_lvl',
            name='Level_ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
