# Generated by Django 3.2.20 on 2023-07-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0003_alter_student_lvl_level_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='Address_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='Student_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
