# Generated by Django 3.2.20 on 2023-07-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0005_alter_student_info_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='Student_Grade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shotokanapp.student_lvl'),
        ),
    ]
